### PR TITLE
update for ConceptNet 5.4; add URIstd for standardization feature

### PR DESCRIPTION
**Pull request by kengz**
Hi, I notice it's been a while since the last update, and there's considerable changes in ConceptNet 5.4. Can you review the PR and publish it so we can use the latest ConceptNet?

changes:
- Update to be compatible with ConceptNet 5.4
- Add [URI standardization](https://github.com/commonsense/conceptnet5/wiki/API#uri-standardization)
- [Search](https://github.com/commonsense/conceptnet5/wiki/API#search) in ConceptNet 5.4 is for finding edges. Update the tests and docs
- update docs and tests

### CODE REVIEW

**Comment by kengz** [comment]
Forgot to mention, this resolves #4

**Comment by kengz** [comment]
@Planeshifter can you pls announce when the new package is published to npm? Would love to use it ASAP thx.

**Comment by Planeshifter** [comment]
Thanks for your additions and help! I am right now improving my code a bit and will publish a new version tonight (in not more than three hours).

**Comment by Planeshifter** [comment]
New version `0.3.0` of the package is online. I changed the name of the `URIstd` method to `getURI` to make it more descriptive.

**Comment by kengz** [comment]
Thanks

**Pull request merged**
